### ISSUE TITLE
tag device='cuda' not working

### ISSUE THREAD

**Issue by arjunsbalaji** [microsoft/evodiff#9]
Hi,

When I specify device=cuda I get an error saying cpu and cuda devices are in use?

I can see that in generate.py .to(device) is being called in inputs and model so not sure why this is happening.

**Comment by sarahalamdari** [comment]
Can you specify which script/function you are running? And I can help solve this

**Comment by colbyford** [comment]
@arjunsbalaji - When running from Python, you can run the following command to set the default Torch device:

```py
import torch
torch.set_default_device('cuda:0')
```

This fixed the cpu/cuda error for me...

**Comment by yangkky** [comment]
@arjunsbalaji do you have an update or more details? Otherwise, I would like to close this.
